remove playwright tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,18 +29,11 @@ jobs:
       - name: Serve Storybook and run tests
         working-directory: storybook
         run: npx -y concurrently -k -s first -n "SB,TEST" -c "magenta,blue" "npx http-server storybook-static --port 6006 --silent" "sleep 15 && npm run test"
-      # run playwright tests
-      - name: Install dependencies
-        run: npm ci
-      - name: Install Playwright Browsers
-        run: npx playwright install --with-deps
-      - name: Run Playwright tests
-        run: npm run test -- --reporter=html
-      - uses: actions/upload-artifact@v3
-        if: always()
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
         with:
-          name: playwright-report
-          path: playwright-report/
+          report_paths: '**/junit.xml'
       # build
       - name: build
         env:
